### ISSUE TITLE
Support for multiple @Entity

### ISSUE THREAD

**Issue by rdebusscher** [soujava/microstream-jakarta-data#1]
Currently, only 1 @Entity is supported, see `ClassScanner`.

Multiple can be supported by using a 'composite' key in the map inside `DataStructure`.

**Comment by otaviojava** [comment]
I like it.

**Comment by rdebusscher** [comment]
But more data in the `DataStorage` and thus even worse performance during saving. `EagerStorer` should not be used on the root object as that stores everything, potential 100's Mb of data for a simple change.

But I have no idea how to avoid it using the interceptor approach.

**Comment by otaviojava** [comment]
Can we update only the entry?

**Comment by rdebusscher** [comment]
Ideal scenario is, using the default `LazyStorer`

- if updating the 'entity', just store the entity itself. But this means it must be the same reference as the one already in the Map (so not a copy with the same id but old == new; the same instance where some other fields can be updated like book title)
- if adding or deleting, store the LazyHashMap reference, it will figure out which element is added or removed (but this is not  super efficient with very large collections)

But this approach is not possible with a generic @Transactional as used on this implementation.

**Comment by otaviojava** [comment]
I've updated it, and now it supports multiple entities.

However, with a single id.

I've removed the `Transactional` approach.
